### PR TITLE
fix: Improve PyPI page render

### LINKED ISSUE #22: Make Markdown look nice on PyPI page

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #22

Example of render working for `pyhf`: https://pypi.org/project/pyhf/

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@drvinceknight @Nikoleta-v3 this is ready for review. Let me know if there are any questions or requested changes.

**Review by drvinceknight — APPROVED** [review]
This looks great thanks :+1:

**Review by Nikoleta-v3 — APPROVED** [review]

**Comment by matthewfeickert** [comment]
Thanks for the super speedy review @drvinceknight @Nikoleta-v3! If for whatever reason this PR _doesn't_ fix things on the next release on PyPI please let me know and I'll be happy to try and debug this.

**Comment by matthewfeickert** [comment]
Seems to be working now, as the render for [`v0.0.6`](https://pypi.org/project/blackbook/0.0.6/) looks to be improved over [`v0.0.5`](https://pypi.org/project/blackbook/0.0.5/).

**Pull request merged**
