### PR TITLE
Add logger output to script.

### LINKED ISSUE #12: Add stdout output
Possibly using a :cake:.

### PR DESCRIPTION
**Pull request by drvinceknight**
This is what it looks like (without color):

```
blackbook(add-log-output): blackbook . 
2019-01-28 17:15:10.857 | INFO     | blackbook.__main__:main:25 - All done! 📖
2019-01-28 17:15:10.857 | INFO     | blackbook.__main__:main:27 - 1 notebooks reformatted. 1 left unchanged.

```

Closes #12 

Once this is in I'll pick up writing some basic documentation.

### CODE REVIEW

**Comment by daffidwilde** [comment]
Is it worth logging which notebooks have been reformatted? Obviously, that can be added in later on so I'm easy either way.

**Comment by drvinceknight** [comment]
Yeah but let's put that under another issue, as is it's as close to how `black` works as I can get it. But I suspect there are options you can pass to black that list the files, we can explore that in #11.

**Comment by Nikoleta-v3** [comment]
If you are happy with the changes @daffidwilde now I can merge :+1:

**Comment by daffidwilde** [comment]
Sounds like a plan :+1:

Go ahead @Nikoleta-v3

**Pull request merged**
